name: KeyXP Giveaway

on:
  workflow_dispatch:

  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run notifier
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python keyxp.py

      - name: Commit cache
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add keyxp_last.json

          git diff --cached --quiet || git commit -m "Update cache"

          git push
